### ISSUE TITLE
Goryon GA and Twtxt v1.0

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#209]
TODO:

- [x] #170 (_Add support for managing a pod's configuration as a pod owner_)
-  [x] https://github.com/jointwt/goryon/issues/16  View external profile while by tapping on external user's name on timeline/discover page
-  [x] https://github.com/jointwt/goryon/issues/17, https://github.com/jointwt/twtxt/issues/210 View external profile while by tapping on external user's name on following/followers page
- [x] Get "reply" string from the backend instead of building it on the frontend

Slated for 5th Oct 2020

**Comment by prologic** [comment]
All done! We're launching!
